/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.project.reactor;

import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class BookServiceTest {

    @Test
    void shouldBeAbleToViewAllPurchasedBooks() {
        BookService bookService = new BookService();
        User user = new User(123);

        Flux<List<Book>> books = bookService.viewPurchased(user.getUserId());

        StepVerifier.create(books).consumeNextWith(
                books1 -> {
                    assertEquals(books1.size(), 1);
                    System.out.println("******"+books1.get(0).getBookName());
                }
        ).verifyComplete();

    }


}
