/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.project.reactor;

import org.junit.jupiter.api.Test;
import reactor.core.publisher.Flux;
import reactor.test.StepVerifier;

import static org.junit.jupiter.api.Assertions.*;

class ProductServiceTest {


    @Test
    void shouldReturnProductFromProductType(){
        ProductService productService = new ProductService();
        Flux<ProductModel> products = productService.searchProducts("electronics");
        assertEquals("mobile" ,products.blockFirst().productName);
    }
}
